# Generated by Django 4.2.27 on 2026-01-14 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExaminerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("acceptance_date", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "examiner_assignments",
            },
        ),
        migrations.CreateModel(
            name="PresentationAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Satisfactory"),
                            ("D", "Pass"),
                            ("F", "Fail"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "presentation_assessments",
            },
        ),
        migrations.CreateModel(
            name="PresentationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "presentation_assignments",
            },
        ),
        migrations.CreateModel(
            name="PresentationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "research_document",
                    models.FileField(
                        upload_to="presentation_documents/research/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "presentation_slides",
                    models.FileField(
                        upload_to="presentation_documents/slides/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "ppt", "pptx"]
                            )
                        ],
                    ),
                ),
                (
                    "plagiarism_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presentation_documents/plagiarism/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("proposed_date", models.DateTimeField()),
                ("alternative_date", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("actual_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("blockchain_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "presentation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresentationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="For virtual presentations", null=True
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "presentation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="presentations.presentationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_schedules",
            },
        ),
    ]
