# Generated by Django 4.2.27 on 2026-02-14 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExaminerAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("acceptance_date", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "examiner_assignments",
            },
        ),
        migrations.CreateModel(
            name="ExaminerChangeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "examiner_change_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable form name", max_length=255
                    ),
                ),
                (
                    "form_role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("supervisor", "Supervisor"),
                            ("examiner", "Examiner"),
                            ("other", "Other"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="JSON payload containing the form fields and values"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "form",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhdAssessmentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sn",
                    models.PositiveIntegerField(
                        help_text="Serial number/order of the assessment item"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the assessment criteria"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        help_text="Maximum score for this assessment item"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "phd_assessment_items",
                "ordering": ["sn"],
            },
        ),
        migrations.CreateModel(
            name="PresentationAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Satisfactory"),
                            ("D", "Pass"),
                            ("F", "Fail"),
                        ],
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "presentation_assessments",
            },
        ),
        migrations.CreateModel(
            name="PresentationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Meet or other virtual meeting link",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Physical venue for in-person presentations",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "presentation_assignments",
            },
        ),
        migrations.CreateModel(
            name="PresentationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "research_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Proposed research title for this presentation",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "research_document",
                    models.FileField(
                        upload_to="presentation_documents/research/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "presentation_slides",
                    models.FileField(
                        upload_to="presentation_documents/slides/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "ppt", "pptx"]
                            )
                        ],
                    ),
                ),
                (
                    "plagiarism_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presentation_documents/plagiarism/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("proposed_date", models.DateTimeField()),
                ("alternative_date", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("actual_date", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Meet or other virtual meeting link",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("blockchain_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "moderator_validation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("did_not_take_place", "Did Not Take Place"),
                        ],
                        default="pending",
                        help_text="Moderator's validation decision: approved (presentation took place) or did_not_take_place",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "moderator_validation_comments",
                    models.TextField(
                        blank=True,
                        help_text="Moderator's comments on the validation",
                        null=True,
                    ),
                ),
                (
                    "moderator_validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the moderator validated this presentation",
                        null=True,
                    ),
                ),
                (
                    "moderator_validation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times moderator has validated this presentation. After 2 validations, only admin or dean can modify.",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresentationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("venue", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="For virtual presentations", null=True
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "presentation_schedules",
            },
        ),
        migrations.CreateModel(
            name="SupervisorAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("acceptance_date", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_assignments",
                        to="presentations.presentationassignment",
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_assignments",
            },
        ),
    ]
