# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("presentations", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="presentation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.presentationtype",
            ),
        ),
    ]
