# Generated by Django 4.2.27 on 2026-02-14 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blockchain", "0003_initial"),
        ("schools", "0001_initial"),
        ("presentations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorassignment",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="presentationschedule",
            name="presentation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="presentations.presentationrequest",
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="moderator_validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who validated this presentation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="presentation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.presentationtype",
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="proposed_examiners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed examiners for this presentation",
                related_name="proposed_examiner_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed supervisors involved in the presentation",
                related_name="presentation_supervisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="viewed_by_coordinators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Coordinators who have viewed this presentation",
                related_name="viewed_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="coordinator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coordinated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="presentation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="presentations.presentationrequest",
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="session_moderator",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator for the presentation session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationassessment",
            name="examiner_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="presentations.examinerassignment",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="blockchain_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="blockchain.blockchainrecord",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forms_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="presentation",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional presentation this form is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="presentations.presentationrequest",
            ),
        ),
        migrations.AddField(
            model_name="examinerchangehistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="examiner_changes_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examinerchangehistory",
            name="new_examiners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Examiners after the change",
                related_name="new_examiner_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examinerchangehistory",
            name="presentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examiner_history",
                to="presentations.presentationrequest",
            ),
        ),
        migrations.AddField(
            model_name="examinerchangehistory",
            name="previous_examiners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Examiners before the change",
                related_name="previous_examiner_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examinerassignment",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examiner_assignments",
                to="presentations.presentationassignment",
            ),
        ),
        migrations.AddField(
            model_name="examinerassignment",
            name="examiner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supervisorassignment",
            unique_together={("assignment", "supervisor")},
        ),
        migrations.AlterUniqueTogether(
            name="presentationassessment",
            unique_together={("examiner_assignment",)},
        ),
        migrations.AlterUniqueTogether(
            name="examinerassignment",
            unique_together={("assignment", "examiner")},
        ),
    ]
