# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("presentations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="coordinator",
            field=models.ForeignKey(
                limit_choices_to={"role": "coordinator"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coordinated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="presentation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="presentations.presentationrequest",
            ),
        ),
        migrations.AddField(
            model_name="presentationassessment",
            name="examiner_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="presentations.examinerassignment",
            ),
        ),
        migrations.AddField(
            model_name="examinerassignment",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examiner_assignments",
                to="presentations.presentationassignment",
            ),
        ),
        migrations.AddField(
            model_name="examinerassignment",
            name="examiner",
            field=models.ForeignKey(
                limit_choices_to={"role": "examiner"},
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="presentationassessment",
            unique_together={("examiner_assignment",)},
        ),
        migrations.AlterUniqueTogether(
            name="examinerassignment",
            unique_together={("assignment", "examiner")},
        ),
    ]
