# Generated by Django 4.2.27 on 2026-03-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="average_mark",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average mark from all examiner evaluations",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="exam_officer_comments",
            field=models.TextField(
                blank=True,
                help_text="Examination officer's comments on approval",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="exam_officer_reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the examination officer reviewed this presentation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="exam_officer_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Examination officer who reviewed this presentation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_officer_reviewed_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="exam_officer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Examination officer approval status",
                max_length=20,
                null=True,
            ),
        ),
    ]
