# Generated by Django 4.2.27 on 2026-01-17 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="proposed_examiners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed examiners for this presentation",
                limit_choices_to={"role": "examiner"},
                related_name="proposed_examiner_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="research_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Proposed research title for this presentation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="presentationrequest",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed supervisors involved in the presentation",
                limit_choices_to={"role": "supervisor"},
                related_name="presentation_supervisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
