# Generated by Django 4.2.27 on 2026-01-19 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0004_presentationrequest_proposed_examiners_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examinerassignment",
            name="examiner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="presentationassignment",
            name="coordinator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coordinated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="presentationrequest",
            name="proposed_examiners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed examiners for this presentation",
                related_name="proposed_examiner_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="presentationrequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="presentationrequest",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposed supervisors involved in the presentation",
                related_name="presentation_supervisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
