# Generated by Django 4.2.27 on 2026-01-19 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0005_alter_examinerassignment_examiner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminerChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="examiner_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_examiners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Examiners after the change",
                        related_name="new_examiner_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiner_history",
                        to="presentations.presentationrequest",
                    ),
                ),
                (
                    "previous_examiners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Examiners before the change",
                        related_name="previous_examiner_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "examiner_change_history",
                "ordering": ["-changed_at"],
            },
        ),
    ]
