# Generated by Django 4.2.27 on 2026-01-19 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0006_examinerchangehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationassignment",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet or other virtual meeting link",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="presentationassignment",
            name="session_moderator",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator for the presentation session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
