# Generated by Django 4.2.27 on 2026-01-20 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presentations", "0007_presentationassignment_meeting_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="viewed_by_coordinators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Coordinators who have viewed this presentation",
                related_name="viewed_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
