# Generated by Django 4.2.27 on 2026-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0008_presentationrequest_viewed_by_coordinators"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationrequest",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet or other virtual meeting link",
                max_length=500,
                null=True,
            ),
        ),
    ]
