# Generated by Django 4.2.27 on 2026-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0009_presentationrequest_meeting_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationassignment",
            name="venue",
            field=models.CharField(
                blank=True,
                help_text="Physical venue for in-person presentations",
                max_length=255,
                null=True,
            ),
        ),
    ]
