# Generated by Django 4.2.27 on 2026-01-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_blockchainrecord_record_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentations', '0011_supervisorassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable form name', max_length=255)),
                ('form_role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('examiner', 'Examiner'), ('other', 'Other')], default='student', max_length=20)),
                ('data', models.JSONField(help_text='JSON payload containing the form fields and values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockchain_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='blockchain.blockchainrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_created', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(blank=True, help_text='Optional presentation this form is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='presentations.presentationrequest')),
            ],
            options={
                'db_table': 'form',
                'ordering': ['-created_at'],
            },
        ),
    ]
