# Generated by Django 4.2.27 on 2026-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0012_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhdAssessmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sn",
                    models.PositiveIntegerField(
                        help_text="Serial number/order of the assessment item"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the assessment criteria"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        help_text="Maximum score for this assessment item"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "phd_assessment_items",
                "ordering": ["sn"],
            },
        ),
    ]
