# Generated by Django migration

from django.db import migrations


def populate_phd_assessment_items(apps, schema_editor):
    """Populate default PhD assessment items"""
    PhdAssessmentItem = apps.get_model('presentations', 'PhdAssessmentItem')
    
    default_items = [
        {
            'sn': 1,
            'description': 'Introduction [Background and Justification]',
            'max_score': 10,
            'is_active': True
        },
        {
            'sn': 2,
            'description': 'Significance of Study [Problem Statement and expected Innovative solution]',
            'max_score': 15,
            'is_active': True
        },
        {
            'sn': 3,
            'description': 'Objectives, Hypotheses/Research Question',
            'max_score': 10,
            'is_active': True
        },
        {
            'sn': 4,
            'description': 'Theoretical and Conceptual Framework & Quality of Literature Review',
            'max_score': 10,
            'is_active': True
        },
        {
            'sn': 5,
            'description': 'Research Methodology\n(i) Proposed research methods are clearly outlined (5)\n(ii) The research/project design, methods of data collection and analysis are appropriate to the aims/objectives of the research/project (5)\n(iii) The methods/Tools used are new/relevant in the field of study (5)',
            'max_score': 15,
            'is_active': True
        },
        {
            'sn': 6,
            'description': 'Potential impact of the research/project to the society and industry\nI. Service/solution/prototype\nII. Commercialization',
            'max_score': 10,
            'is_active': True
        },
        {
            'sn': 7,
            'description': 'Realistic timelines',
            'max_score': 5,
            'is_active': True
        },
        {
            'sn': 8,
            'description': 'Dissemination plan to stakeholders, wider public and to the community studied\n(i) Publications/leaflets/knowledge exchange/meetings (3)\n(ii) Policy briefs to inform policy makers (2)',
            'max_score': 5,
            'is_active': True
        },
        {
            'sn': 9,
            'description': 'A detailed and feasible budget and a clear justification of expenditures',
            'max_score': 5,
            'is_active': True
        },
        {
            'sn': 10,
            'description': 'Evidence of Originality and creativity',
            'max_score': 10,
            'is_active': True
        },
        {
            'sn': 11,
            'description': 'Organization of the research proposal',
            'max_score': 5,
            'is_active': True
        },
    ]
    
    for item_data in default_items:
        PhdAssessmentItem.objects.create(**item_data)


def reverse_populate(apps, schema_editor):
    """Remove all PhD assessment items"""
    PhdAssessmentItem = apps.get_model('presentations', 'PhdAssessmentItem')
    PhdAssessmentItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0013_add_phd_assessment_items'),
    ]

    operations = [
        migrations.RunPython(populate_phd_assessment_items, reverse_populate),
    ]
