# Generated by Django 4.2.27 on 2026-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0016_add_moderator_validation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentationrequest",
            name="moderator_validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("did_not_take_place", "Did Not Take Place"),
                ],
                default="pending",
                help_text="Moderator's validation decision: approved (presentation took place) or did_not_take_place",
                max_length=20,
                null=True,
            ),
        ),
    ]
