# Generated by Django 4.2.27 on 2026-02-13 14:17

from django.db import migrations


def initialize_validation_counts(apps, schema_editor):
    """Initialize validation counts for existing presentations"""
    PresentationRequest = apps.get_model('presentations', 'PresentationRequest')
    
    # Set count to 1 for already validated presentations
    for presentation in PresentationRequest.objects.all():
        if presentation.moderator_validated_at is not None:
            presentation.moderator_validation_count = 1
        else:
            presentation.moderator_validation_count = 0
        presentation.save(update_fields=['moderator_validation_count'])


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0017_update_moderator_validation_choices"),
    ]

    operations = [
        # Note: moderator_validation_count field already exists in database
        # Initialize validation counts for existing records
        migrations.RunPython(
            initialize_validation_counts,
            reverse_code=migrations.RunPython.noop
        ),
    ]
