# Generated by Django 4.2.27 on 2026-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0018_add_validation_count_and_blockchain_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationrequest',
            name='moderator_validation_count',
            field=models.IntegerField(default=0, help_text='Number of times moderator has validated this presentation. After 2 validations, only admin or dean can modify.'),
        ),
    ]
