# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockchainRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.BigIntegerField(unique=True)),
                ("previous_hash", models.CharField(max_length=256)),
                ("current_hash", models.CharField(max_length=256, unique=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("user_creation", "User Creation"),
                            ("user_update", "User Update"),
                            ("presentation_submission", "Presentation Submission"),
                            ("presentation_scheduled", "Presentation Scheduled"),
                            ("assessment_submitted", "Assessment Submitted"),
                            ("notification_sent", "Notification Sent"),
                            ("date_changed", "Date Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("record_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "blockchain_records",
                "ordering": ["block_number"],
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("presentation_rules", "Presentation Rules"),
                            ("assessment_rules", "Assessment Rules"),
                            ("notification_rules", "Notification Rules"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contract_code", models.TextField()),
                ("contract_hash", models.CharField(max_length=256, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "smart_contracts",
            },
        ),
    ]
