# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blockchain", "0001_initial"),
        ("presentations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchainrecord",
            name="presentation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blockchain_records",
                to="presentations.presentationrequest",
            ),
        ),
    ]
