# Generated by Django 4.2.27 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("user_creation", "User Creation"),
                    ("user_update", "User Update"),
                    ("role_creation", "Role Creation"),
                    ("role_update", "Role Update"),
                    ("role_deletion", "Role Deletion"),
                    ("presentation_submission", "Presentation Submission"),
                    ("presentation_scheduled", "Presentation Scheduled"),
                    ("assessment_submitted", "Assessment Submitted"),
                    ("notification_sent", "Notification Sent"),
                    ("date_changed", "Date Changed"),
                ],
                max_length=50,
            ),
        ),
    ]
