# Generated by Django 4.2.27 on 2026-02-12 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0004_alter_blockchainrecord_record_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrecord",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="smartcontract",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
