# Generated by Django 4.2.27 on 2026-02-14 06:12

import apps.users.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with this email already exists."
                        },
                        help_text="User's email address (must be unique)",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("prof", "Prof"),
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("ms", "Ms"),
                            ("", "None"),
                        ],
                        default="",
                        help_text="User's title (Dr, Prof, Mr, Mrs, Ms)",
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Student registration number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Email verified"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Profile approved by admin/admission"
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when profile was approved",
                        null=True,
                    ),
                ),
                (
                    "password_changed",
                    models.BooleanField(
                        default=False,
                        help_text="User has changed password from default",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_login_date", models.DateTimeField(blank=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="User has been soft deleted"
                    ),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when user was deleted", null=True
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("blockchain_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Admission officer who approved this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who deleted this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="schools.programme",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-date_created"],
            },
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., student, supervisor, admin)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name for the role", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("blockchain_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="Secure Progress Management System", max_length=255
                    ),
                ),
                (
                    "system_email",
                    models.EmailField(default="admin@nm-aist.ac.tz", max_length=254),
                ),
                ("system_url", models.URLField(default="http://localhost:4200")),
                (
                    "max_presentations",
                    models.IntegerField(
                        default=3, help_text="Maximum presentations per student"
                    ),
                ),
                (
                    "presentation_duration",
                    models.IntegerField(
                        default=20, help_text="Presentation duration in minutes"
                    ),
                ),
                (
                    "qa_duration",
                    models.IntegerField(
                        default=10, help_text="Q&A duration in minutes"
                    ),
                ),
                (
                    "email_on_registration",
                    models.BooleanField(
                        default=True, help_text="Send email on user registration"
                    ),
                ),
                (
                    "email_on_presentation_request",
                    models.BooleanField(
                        default=True, help_text="Send email on presentation request"
                    ),
                ),
                (
                    "email_on_approval",
                    models.BooleanField(
                        default=True, help_text="Send email on presentation approval"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "programme_level",
                    models.CharField(
                        choices=[("masters", "Masters"), ("phd", "PhD")],
                        default="masters",
                        max_length=20,
                    ),
                ),
                ("admission_year", models.IntegerField()),
                ("enrollment_year", models.IntegerField()),
                ("expected_graduation", models.DateField()),
                ("is_active_student", models.BooleanField(default=True)),
                (
                    "is_admitted",
                    models.BooleanField(
                        default=False,
                        help_text="Student has been admitted by admission officer",
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("total_presentations", models.IntegerField(default=0)),
                ("completed_presentations", models.IntegerField(default=0)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_resets",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's roles/groups - can have multiple except students (students must be student-only)",
                related_name="group_users",
                to="users.usergroup",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="SupervisorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("total_supervised", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supervisor_profiles",
                "unique_together": {("user", "specialization")},
            },
        ),
        migrations.CreateModel(
            name="ExaminerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialization", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("total_assessments", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiner_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "examiner_profiles",
                "unique_together": {("user", "specialization")},
            },
        ),
        migrations.CreateModel(
            name="CoordinatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinators",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coordinator_profiles",
                "unique_together": {("user", "school")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("ASSIGN", "Assign"),
                            ("SUBMIT", "Submit"),
                            ("SCHEDULE", "Schedule"),
                            ("SEND", "Send"),
                            ("EXPORT", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model affected", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of the object", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON of changes (before/after for updates)",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "blockchain_block_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                ],
            },
        ),
    ]
