# Generated by Django 4.2.27 on 2026-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number_deleted_original",
            field=models.CharField(
                blank=True,
                help_text="Original phone number before deletion",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
