# Generated by Django 4.2.27 on 2026-01-14 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_custom_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["-date_created"]},
        ),
    ]
