# Generated by Django 4.2.27 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_studentprofile_address_studentprofile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="allow_concurrent_presentations",
            field=models.BooleanField(
                default=False,
                help_text="Allow students to request a new presentation before the current one is completed",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_examiners",
            field=models.IntegerField(
                default=2,
                help_text="Maximum number of proposed examiners per presentation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_supervisors",
            field=models.IntegerField(
                default=2, help_text="Maximum number of supervisors per presentation"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="min_examiners",
            field=models.IntegerField(
                default=0,
                help_text="Minimum number of proposed examiners per presentation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="min_supervisors",
            field=models.IntegerField(
                default=2, help_text="Minimum number of supervisors per presentation"
            ),
        ),
    ]
