# Generated by Django 4.2.27 on 2026-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_admitted",
            field=models.BooleanField(
                default=False,
                help_text="Student has been admitted by admission officer",
            ),
        ),
    ]
