# Generated by Django 4.2.27 on 2026-03-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_supervisor_examiner_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, help_text="Gender", max_length=20, null=True
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_mobile",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_email_secondary",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short professional biography", null=True
                    ),
                ),
                ("nok_name", models.CharField(blank=True, max_length=255, null=True)),
                ("nok_mobile", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nok_relation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
