# Generated by Django 4.2.27 on 2026-03-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_profile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='Academic Progress Report Management System', max_length=255),
        ),
    ]
