# Generated by Django 4.2.27 on 2026-01-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin/Admission officer who approved this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when profile was approved", null=True
            ),
        ),
    ]
