# Generated by Django 4.2.27 on 2026-01-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_approved_by_customuser_approved_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dr", "Dr"),
                    ("prof", "Prof"),
                    ("mr", "Mr"),
                    ("mrs", "Mrs"),
                    ("ms", "Ms"),
                    ("", "None"),
                ],
                default="",
                help_text="User's title (Dr, Prof, Mr, Mrs, Ms)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's roles/groups (can have multiple except students)",
                related_name="group_users",
                to="users.usergroup",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_group",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary role/group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.usergroup",
            ),
        ),
    ]
