# Generated by Django 4.2.27 on 2026-01-19 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0003_alter_school_contact_email"),
        ("users", "0010_remove_deprecated_role_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatorprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's roles/groups - can have multiple except students (students must be student-only)",
                related_name="group_users",
                to="users.usergroup",
            ),
        ),
        migrations.AlterField(
            model_name="examinerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examiner_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supervisorprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coordinatorprofile",
            unique_together={("user", "school")},
        ),
        migrations.AlterUniqueTogether(
            name="examinerprofile",
            unique_together={("user", "specialization")},
        ),
        migrations.AlterUniqueTogether(
            name="supervisorprofile",
            unique_together={("user", "specialization")},
        ),
    ]
