# Generated by Django 4.2.27 on 2026-01-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_coordinatorprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who deleted this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when user was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="User has been soft deleted"
            ),
        ),
    ]
