# Generated by Django 4.2.27 on 2026-01-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_customuser_deleted_by_customuser_deleted_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="blockchain_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="blockchain_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("ASSIGN", "Assign"),
                            ("SUBMIT", "Submit"),
                            ("SCHEDULE", "Schedule"),
                            ("SEND", "Send"),
                            ("EXPORT", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model affected", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of the object", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON of changes (before/after for updates)",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "blockchain_block_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                ],
            },
        ),
    ]
