# Generated by Django 4.2.27 on 2026-02-04 14:37

from django.db import migrations, models
from django.db.models import Count


def handle_duplicate_emails(apps, schema_editor):
    """
    Handle existing duplicate emails before adding unique constraint.
    For duplicates, append a suffix to older records: email -> email_1, email_2, etc.
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    db_alias = schema_editor.connection.alias
    
    # Find emails that appear more than once
    duplicate_emails = (
        CustomUser.objects.using(db_alias)
        .values('email')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicate_emails:
        email = dup['email']
        # Get all users with this email, ordered by date_created (oldest first)
        users_with_email = CustomUser.objects.using(db_alias).filter(email=email).order_by('date_created')
        
        # Keep the first (oldest) user with the original email
        # Modify the rest
        for index, user in enumerate(users_with_email[1:], start=1):
            # Append suffix to make email unique
            new_email = f"{email.split('@')[0]}_{index}@{email.split('@')[1]}"
            user.email = new_email
            user.save(using=db_alias)
            print(f"Updated duplicate email: {email} -> {new_email} for user {user.username}")


def reverse_func(apps, schema_editor):
    """
    Reverse migration - this is a no-op since we can't reliably restore
    the original duplicate emails
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_usergroup_permissions"),
    ]

    operations = [
        # First, handle any existing duplicate emails
        migrations.RunPython(handle_duplicate_emails, reverse_func),
        
        # Then add the unique constraint
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with this email already exists."},
                help_text="User's email address (must be unique)",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
