# Generated by Django 4.2.27 on 2026-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
