# Generated by Django 4.2.27 on 2026-01-19 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0003_alter_school_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="dean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_dean",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
