# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("download", "Download"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.BigIntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("progress_chart", "Progress Chart"),
                            ("statistics_card", "Statistics Card"),
                            ("timeline", "Timeline"),
                            ("recent_activities", "Recent Activities"),
                            ("notifications", "Notifications"),
                            ("quick_actions", "Quick Actions"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                ("position", models.IntegerField(default=0, help_text="Display order")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("supervisor", "Supervisor"),
                            ("coordinator", "Coordinator"),
                            ("moderator", "Moderator"),
                            ("examiner", "Examiner"),
                            ("dean", "Dean"),
                            ("qa", "Quality Assurance"),
                            ("auditor", "Auditor"),
                            ("admission", "Admission Officer"),
                            ("vice_chancellor", "Vice Chancellor"),
                            ("admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dashboard_widgets",
                "ordering": ["role", "position"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("student_progress", "Student Progress Report"),
                            ("supervisor_overview", "Supervisor Overview"),
                            ("presentation_statistics", "Presentation Statistics"),
                            ("examiner_performance", "Examiner Performance"),
                            ("school_overview", "School Overview"),
                            ("system_audit", "System Audit Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("report_data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
