# Generated by Django 4.2.27 on 2026-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("presentation_request", "Presentation Request"),
                            ("presentation_accepted", "Presentation Accepted"),
                            ("presentation_declined", "Presentation Declined"),
                            ("examiner_assignment", "Examiner Assignment"),
                            ("date_changed", "Presentation Date Changed"),
                            (
                                "time_warning",
                                "Time Warning - Presentation Starting Soon",
                            ),
                            ("assessment_submitted", "Assessment Submitted"),
                            ("new_profile", "New Profile Awaiting Approval"),
                            ("profile_approved", "Profile Approved"),
                            ("profile_rejected", "Profile Rejected"),
                            ("system_message", "System Message"),
                            ("presentation_completed", "Presentation Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("notify_presentation_request", models.BooleanField(default=True)),
                ("notify_examiner_assignment", models.BooleanField(default=True)),
                ("notify_date_changes", models.BooleanField(default=True)),
                ("notify_time_warnings", models.BooleanField(default=True)),
                ("notify_assessment_submitted", models.BooleanField(default=True)),
                ("notify_new_profiles", models.BooleanField(default=True)),
                ("time_warning_minutes", models.IntegerField(default=30)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
    ]
