# Generated by Django 4.2.27 on 2026-02-14 06:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("presentation_request", "Presentation Request"),
                            ("presentation_accepted", "Presentation Accepted"),
                            ("presentation_declined", "Presentation Declined"),
                            ("examiner_assignment", "Examiner Assignment"),
                            ("date_changed", "Presentation Date Changed"),
                            ("time_warning", "Presentation Starting Soon"),
                            ("assessment_submitted", "Assessment Submitted"),
                            ("new_profile", "New Profile Awaiting Approval"),
                            ("profile_approved", "Profile Approved"),
                            ("profile_rejected", "Profile Rejected"),
                            ("presentation_completed", "Presentation Completed"),
                            ("system_message", "System Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Angular route to open when user clicks 'See more'",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("minutes_before", models.IntegerField()),
                (
                    "channel",
                    models.CharField(help_text="Email or in-app", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        default="sent", help_text="sent or failed", max_length=20
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reminder_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
