# Generated by Django 4.2.27 on 2026-02-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("presentations", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderlog",
            name="presentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="presentations.presentationrequest",
            ),
        ),
    ]
