# Generated by Django 4.2.27 on 2026-01-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0011_supervisorassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.IntegerField(default=15)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In App')], default='email', max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=32)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='presentations.presentationrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
