# Generated by Django 4.2.27 on 2026-02-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('presentations', '0014_populate_phd_assessment_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_reminderlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_assessment_submitted',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_date_changes',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_examiner_assignment',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_new_profiles',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_presentation_request',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_time_warnings',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_start',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='time_warning_minutes',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text="Angular route to open when user clicks 'See more'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('presentation_request', 'Presentation Request'), ('presentation_accepted', 'Presentation Accepted'), ('presentation_declined', 'Presentation Declined'), ('examiner_assignment', 'Examiner Assignment'), ('date_changed', 'Presentation Date Changed'), ('time_warning', 'Presentation Starting Soon'), ('assessment_submitted', 'Assessment Submitted'), ('new_profile', 'New Profile Awaiting Approval'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('presentation_completed', 'Presentation Completed'), ('system_message', 'System Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='channel',
            field=models.CharField(help_text='Email or in-app', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='minutes_before',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentationrequest'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.CharField(default='sent', help_text='sent or failed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_archived'], name='notificatio_recipie_d51e24_idx'),
        ),
    ]
