# Generated by Django 4.2.27 on 2026-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("presentation_request", "Presentation Request"),
                    ("presentation_accepted", "Presentation Accepted"),
                    ("presentation_declined", "Presentation Declined"),
                    ("examiner_assignment", "Examiner Assignment"),
                    ("date_changed", "Presentation Date Changed"),
                    ("time_warning", "Presentation Starting Soon"),
                    ("assessment_submitted", "Assessment Submitted"),
                    ("new_profile", "New Profile Awaiting Approval"),
                    ("profile_approved", "Profile Approved"),
                    ("profile_rejected", "Profile Rejected"),
                    ("presentation_completed", "Presentation Completed"),
                    ("new_student_registration", "New Student Registration"),
                    ("system_message", "System Message"),
                ],
                max_length=50,
            ),
        ),
    ]
