# Generated by Django 4.2.27 on 2026-02-12 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="reminderlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
